import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container:{
        backgroundColor:"#edebeb",
        flex:1
    },
    navBar:{
        width:'100%',
        height:'75px',
        backgroundColor:'rgb(15, 27, 34)',

    },
    data:{
        fontSize:'15px',
        fontWeight:'500',
        marginLeft:'7px',
        marginTop:'3px',
        color:'white'
    },
    textEv:{
        fontSize:'30px',
        fontWeight:'bold',
        color:'white'
    },
    portifolio:{
        width:'100%',
        height:'220px',
        backgroundColor:'#edebeb',
        display:'flex',
        alignItems:"center",
        justifyContent:'center'
    },
    subPortifolio:{
        width:'77%',
        height:'65%',
        backgroundColor:'green',
        borderRadius:'30px',
        display:'flex',
        flexDirection:'row',
        justifyContent:'space-between'
    },

    textPor:{
        fontSize:'15px',
        color:'white'
    },
    textMo:{
        fontSize:'30px',
        fontWeight:'bold',
        color:'white'
    },
    subText:{
        width:'20',
        height:'20',
        backgroundColor:'',
        display:"flex",
        justifyContent:'center'
    },
    subText02:{
        width:'20',
        height:'20',
        backgroundColor:'',
        display:'flex',
        justifyContent:'center',
        marginRight:'5px'
    },
    subTextMo:{
        color:'white'
    },
    subTextPor:{
        marginLeft:'12px',
        fontSize:'19px',
        color:'white'
    },
    subContainer:{
        width:'100%',
        height:'100%',
        backgroundColor:'#edebeb'
    },
    textNe:{
        fontSize:'25px',
        fontWeight:'bold',
        marginLeft:'10px',
    },
    textAl:{
        fontSize:'17px',
        fontWeight:'bold',
        marginTop:'7px',
        marginRight:'13px',
        color:'blue',
        textDecorationLine:'underline',
        textDecorationColor:'blue'
    },
    texto:{
        display:'flex',
        flexDirection:"row",
        justifyContent:"space-between",
        color:'white'
    },
    subImgAp:{
        width:360,
        height:170,
        borderRadius:'10px',
        shadowColor: 'black',
        shadowOffset: {width: -2, height: 4},
        shadowOpacity: 4,
        shadowRadius: 3,
    },
    imgAp:{
        width:'100%',
        height:'200px',
        display:'flex',
        alignItems:'center',
        justifyContent:'center'
    },
    stocks:{
        width:'100%',
        height:'50px',
        backgroundColor:'#edebeb'
    },
    textSt:{
        fontWeight:'bold',
        fontSize:'24px',
        
    },
    subInsterprise:{
        width:'19pc',
        height:'60px',
        borderRadius:'30px',
        backgroundColor:'white',
        display:'flex',
        flexDirection:"row",
        alignItems:'center'
       
    },
    subStocks:{
        width:'100%',
        height:'15pc',
        backgroundColor:'#edebeb',
        display:'flex',
        flexDirection:'column',
        alignItems:'center',
        justifyContent:'space-evenly'
    },
    icon:{
        width:'46px',
        height:'45px',
        backgroundColor:"",
        marginLeft:'7px',
        borderRadius:'10px',
        display:'flex',
        alignItems:"center",
        justifyContent:'center'
    },
    textIn:{
        marginLeft:'11px',
        marginRight:'10px',
        fontSize:'19px',
        fontWeight:"bold"
    }
})
export default styles